apiVersion: v1
kind: ConfigMap
metadata:
  name: mavenwebconfig
  namespace: beta
data:
  MAVEN_USER_NAME= "MAPR"
  MAVEN_PASSWD= "MBR"
 MAVEN_DETAILS: |
   PROJECT="MAPR",
   TEAM="MBR",
   TEAM_SIZE="6",
   COMPANY_NAME="MAPR"
