apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
spec:
 storageClassName: gp2  
 accessModes:
 - ReadWriteMany
 capacity:
    storage: 1Gi
 persistentVolumeReclaimPolicy: Delete
 hostPath:
  path: /mbrdev
